// Generated by helper/item_editor.py. Edit source/items_project.json instead.
package dev.lotcarnage.culinaryexpansion;
import net.minecraft.world.food.FoodProperties;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.CreativeModeTabs;
import net.minecraft.world.item.component.Consumable;
import net.minecraft.world.item.consume_effects.ApplyStatusEffectsConsumeEffect;
import net.minecraft.world.effect.MobEffectInstance;
import net.minecraft.world.effect.MobEffects;
import net.minecraftforge.event.BuildCreativeModeTabContentsEvent;
import net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;
public final class ModItems {
    public static final String MOD_ID = "culinary_expansion";
    public static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, MOD_ID);
    public static final RegistryObject<Item> FRIED_EGG = ITEMS.register("fried_egg", () -> new Item(new Item.Properties().setId(ITEMS.key("fried_egg")).stacksTo(64).food(new FoodProperties.Builder().nutrition(2).saturationModifier(0.6F).build(), Consumable.builder().consumeSeconds(1.6F).build())));
    public static final RegistryObject<Item> CHOCOLATE = ITEMS.register("chocolate", () -> new Item(new Item.Properties().setId(ITEMS.key("chocolate")).stacksTo(64).food(new FoodProperties.Builder().nutrition(1).saturationModifier(0.1F).build(), Consumable.builder().consumeSeconds(0.5F).build())));
    public static void register(FMLJavaModLoadingContext context) {
        ITEMS.register(context.getModBusGroup());
        BuildCreativeModeTabContentsEvent.BUS.addListener(ModItems::addFood);
    }
    private static void addFood(BuildCreativeModeTabContentsEvent event) {
        if (event.getTabKey() == CreativeModeTabs.FOOD_AND_DRINKS) {
            event.accept(FRIED_EGG);
            event.accept(CHOCOLATE);
        }
    }
}
